### ISSUE TITLE
pipe error

### ISSUE THREAD

**Issue by MrApe** [scotthartley/pandoc-wrapfig#1]
Hi, 
running pandoc with `pandoc --filter /usr/local/bin/pandoc-wrapfig.py`gives the following error on OS X (10.11.5): 

```
pandoc: Error running filter /usr/local/bin/pandoc-wrapfig.py
fd:4: hPutBuf: resource vanished (Broken pipe)
```

Any suggestions?
Best

Jonas

**Comment by scotthartley** [comment]
Sorry for the delay in getting back to you—I was out of the country. I'm 
honestly not sure what is causing this. Does this happen even with the 
example files I posted?

Jonas Schwartze wrote:

**Comment by meereeum** [comment]
@MrApe temporary solution, fwiw:

```
$ pandoc thing.md -t json | python ./txtWrap.py | pandoc -f json -o thing.pdf
```

Might be caused by not flushing STDOUT ? (see https://github.com/tomduck/pandoc-eqnos/issues/4)

**Comment by scotthartley** [comment]
Thanks very much! I've flushed the stdout at the end of the script. Please let me know if this works—as I could not reproduce the problem, I can't actually tell if this fixed it.

**Comment by meereeum** [comment]
hmm, no luck.

I get:

```
pandoc: Error running filter ./pandoc-wrapfig.py
fd:4: hClose: resource vanished (Broken pipe)
```

**Comment by scotthartley** [comment]
Shoot. There's a discussion of a similar issue here:

https://groups.google.com/forum/#!msg/pandoc-discuss/_DzYze7HqwU/NXKxsK5lCwAJ

Which implicates either a problem specifying the location of the filter or a filter that is not executable. Does that help?

**Comment by meereeum** [comment]
sadly, no :/ (script is executable and am passing full path/to/filter).

**Comment by scotthartley** [comment]
What OS, version of python, etc., are you using?

**Comment by meereeum** [comment]
tried with `Debian Jessie + Python 2.7` and `OS X El Capitan + Python {2.7, 3.5}`

**Comment by scotthartley** [comment]
Really wish I could help, but the OSX system at least is pretty much exactly what I'm using. Sorry!

**Comment by bart1** [comment]
I have found the error to be solved when pandocfilters got installed python3-pandocfilters on ubuntu

**Comment by scotthartley** [comment]
Excellent. Thanks!
