### ISSUE TITLE
Not so obvious how to install on macOS.

### ISSUE THREAD

**Issue by stanislaw** [scotthartley/pandoc-wrapfig#4]
Hi,

Thanks for creating this project. It seems to work for me.

I appreciate your sense of humor:

> Obviously, the wrapfig package must be installed.

It seems obvious indeed that I have to install the package but not really obvious what is the right way to do that.

This is how I made it work for me, but is this a recommended to install `pandoc-wrapfig` on macOS system?

```
sudo easy_install pip
sudo pip install pandocfilters
wget https://raw.githubusercontent.com/scotthartley/pandoc-wrapfig/master/pandoc-wrapfig.py
pandoc -o out/result.pdf \
           --pdf-engine=xelatex \
           --from markdown+yaml_metadata_block \
           --filter pandoc-wrapfig.py \
           content/*.md content/00-metadata.yml
```

In YAML:

```yml
# ...
header-includes:
  - \usepackage{float}
  - \usepackage{wrapfig}
```

Thanks.

**Comment by scotthartley** [comment]
Actually, I wasn't being quite as droll as you give me credit for. I was referring to the _LaTeX_ "wrapfig" package, which is probably included in whatever TeX distribution people are using but can be installed with tlmgr if not.

What you've done looks fine: installation of the filter itself is fairly trivial as it can just be downloaded from github or even copied/pasted into a text file.
